#include <stdio.h>

/**
 * printFibonacci - is a function that prints the Fibonacci series up to
 * a given count 'n'.
 *
 * NOTE - A Fibonacci series is a sequence of numbers in which each number
 * is the sum of the two preceding numbers, starting from 0 and 1.
 * The sequence typically begins with 0 and 1, and the subsequent numbers
 * are generated by adding the previous two numbers.
 * EXAMPLES - 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, ...
 *
 * main - calls the 'printFibonacci' function
 */

//Function declaratio
int printFibonacci()
